#!/bin/bash

CHECK=$(systemctl status | head -n 2 | awk -F 'State: ' '{print $2}')
STATUS=$(echo $CHECK)

critical ()
        {

        echo "CRITICAL"
        echo "Status: $STATUS"
        systemctl | grep failed | awk -F '●' '{print $2}' | awk -F ' ' '{print $1}'
        exit 2

        }

warn ()
        {

        echo "WARNING"
        echo "Status: $STATUS"
        exit 1

        }

good ()
        {

        echo "OK"
        echo "Status: $STATUS"
        exit 0

        }

main ()
        {

        if [[ $STATUS = "running" ]]; then
                good;
        else
                if [[ $STATUS = "starting" ]]; then
                        warn;
                else
                        critical;
                fi
        fi

        }

main;
