#!/bin/bash

CHECK=$(systemctl status | awk -F 'State:' '{print $2}' | awk -F '{' '{print $1}')
STATUS=$(echo $CHECK)

critical ()
        {

        echo "CRITICAL"
        echo "Status: $STATUS"
        systemctl | grep failed | awk -F '●' '{print $2}' | awk -F ' ' '{print $1}'
        exit 2

        }

good ()
        {

        echo "OK"
        echo "Status: $STATUS"
        exit 0

        }

main ()
        {

        if [[ $STATUS = "running" ]]; then
                good;
        else
                critical;
        fi

        }

main;
